### ISSUE TITLE
Standalone composer.json migration

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-migration#21]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Hey guys, I would prefer having a dedicated composer migration to avoid such issues as in #20 aswell as the missing migration of the `extra.zf` part within the `composer.json`.

Which project should I start working on to implement such a "feature"? Not sure if the `zendframework-bridge` (which is actually used to provide the replacement stuff) should be extended or just handling it in this migration tool.

Or is the `extra.zf` key handled in some other package already?

**Comment by weierophinney** [comment]
This would be the correct project to add that, particularly as it already has the code for updating the `composer.json` in it.

What do you mean by the "missing migration of the `extra.zf` part within the `composer.json`"? Can you detail that, please?

(The bridge only contains the replacement rules; this was done so we could re-use them both in the bridge — where they're used for the config post-processing and autoloading), in our repository transfer tooling, and here.)

**Comment by boesing** [comment]
@weierophinney There are many packages which provides informations to the `zendframework/zend-component-installer` which is superseeded by the `laminas/laminas-component-installer`.

Those informations are stored in the `composer.json` `extra.zf` key. 
Just wondering if `extra.zf` is being "migrated" already in another way (I did not checked yet, but after running the tool, the `extra.zf` remains untouched in my `composer.json`).

**Comment by weierophinney** [comment]
In this case, laminas-component-installer was rewritten in such a way that it will look for both the `extra.zf` and `extra.laminas` keys, so you're covered! This was done to ensure we continue to work with 3rd party packages in the ecosystem.

We will be writing a package migration guide in the near future that will detail that this is a manual change to make.

**Comment by boesing** [comment]
Perfect. I am fine with manually fixing my composer.jsons 
Just wanted to drop a note here that some but not all "zend-" prefixed Packages of 3rd party packages are getting renamed.
Thanks for having a look on it.
