### ISSUE TITLE
Not migrated escaped namespace

### ISSUE THREAD

**Issue by snapshotpl** [laminas/laminas-migration#26]
I have auto-generated baseline for phpstan. This file still contains old Zend namespaces.

`message: "#^PHPDoc tag @var for variable \\$query has no value type specified in iterable type Zend\\\\Stdlib\\\\Parameters\\.$#"`

**Comment by weierophinney** [comment]
We actually have rules for this: https://github.com/laminas/laminas-zendframework-bridge/blob/master/config/replacements.php#L143

I'm not sure how many more rules we want to make for differing amounts of escape sequences. 

Can you provide the filename and contents so we can try and determine why it's not getting migrated properly, please?

**Comment by snapshotpl** [comment]
In my project it's `phpstan-baseline.neon`. File content:

```neon
parameters:
	ignoreErrors:
		-
			message: "#^PHPDoc tag @var for variable \\$query has no value type specified in iterable type Zend\\\\Stdlib\\\\Parameters\\.$#"
			count: 2
			path: module/Application/src/ApiParamsListener.php
```

**Comment by snapshotpl** [comment]
I believe that https://github.com/laminas/laminas-zendframework-bridge/blob/master/config/replacements.php#L143 replace duble backslashes - another two are for escape backslashes.
