### ISSUE TITLE
Incorrect array key in module.config.php after upgrade

### ISSUE THREAD

**Issue by adear11** [laminas/laminas-migration#33]
### Bug Report

|    Q |   A
|--------------------------- | ------
| laminas-migrations  | 1.0.2
| api-tools                   | 1.4.0
| api-tools-admin        | 1.8.0
| api-tools-admin-ui    | 1.3.13

#### Summary

I recently upgraded an Apigility project to laminas-api-tools. The upgrade broke some db-connected resources in my project. Digging into it, I found that the migration tool moved the `zf-apigility` array key in `module.config.php` to `laminas-api-tools` so that the file went from this:
```PHP
...
'zf-apigility' => array(
        'db-connected' => array(
            ...
       )
)
...
```
to this:
```PHP
...
'laminas-api-tools' => array(
        'db-connected' => array(
            ...
       )
)
...
```

This change results in this error when the resource is requested:

`[error] 21#21: *190 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Laminas\ServiceManager\Exception\ServiceNotFoundException: Laminas\ApiTools\Rest\Factory\RestControllerFactory::canCreate requires that a valid "listener" service be specified for controller QReview\V1\Rest\ContentArea\Controller; no service found in /var/www/html/vendor/laminas-api-tools/api-tools-rest/src/Factory/RestControllerFactory.php:78`

I created a new db-connected resource via admin tools, and it created the key `api-tools` in `module.config.php`. Once I moved the configuration for my db-connected resources from the `laminas-api-tools` key to the `api-tools` key, they started working again.

It would appear that either the migrations tools isn't using the correct name for the new, converted key, or what ever package it is that reads this config file isn't looking for the correct key name.

**Comment by michalbundyra** [comment]
@adear11 Thanks for reporting. It is a bug, indeed.

We need to find the correct solution but here is the evidence:
https://github.com/laminas/laminas-zendframework-bridge/blob/master/config/replacements.php#L492-L493

https://github.com/laminas-api-tools/api-tools/blob/master/config/module.config.php#L49

So migration tool should replace it also to `api-tools`, not `laminas-api-tools`.

/cc @weierophinney

**Comment by weierophinney** [comment]
I believe those two lines are incorrect, but I'll got double-check the repos before I make a PR around this.
