### ISSUE TITLE
Local installation in the project as local dependency doesn't work

### ISSUE THREAD

**Issue by rarog** [laminas/laminas-migration#35]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.2

#### Summary

Local installation via composer as local dependency works per se, but because in the process vendor directory is removed, laminas-migration throws errors.

#### Current behavior

PHP Fatal error:  Uncaught Error: Class 'Laminas\Migration\DependencyPlugin' not found in /home/myuser/path/to/my/project/vendor/laminas/laminas-migration/src/Command/MigrateCommand.php:219

#### How to reproduce

Get any project that would have to be migrated from ZF to Laminas and install laminas-migration as local dependency in the project itself.

#### Expected behavior

Run as local dependency by deleting everything in vendor besides stuff needed for laminas-migration.
Or remove this variant from the documentation at https://docs.laminas.dev/migration

**Comment by michalbundyra** [comment]
@rarog Thanks for reporting.
Local installation has been removed from migration guide. Please use global installation or clone as described in https://docs.laminas.dev/migration/#install-laminas-migration

Thanks!
