### ISSUE TITLE
Undefined class constant 'PRE_COMMAND_RUN' in DependencyRewriterPlugin.php

### ISSUE THREAD

**Issue by dbierer** [laminas/laminas-migration#40]
### Bug Report

|    Q        |   A
|------------ | ------
| laminas-migration  | 1.0.3
| PHP  | 7.4.3 
| Composer | 1.6

#### Summary
Encountering error: `Undefined class constant 'PRE_COMMAND_RUN' in DependencyRewriterPlugin.php:63` when running `laminas-migration migrate` on an existing Apigility project. Migration is successful on PHP 7.2.  Error occurs when running the same migration on PHP 7.4.3.

#### Solution
Upgraded to Composer version 1.10.x.  Migration completed successfully, `composer install` worked OK.  Application functions normally post-migration to Laminas.

**Comment by weierophinney** [comment]
I suspect you're using a dated version of composer. Please run `composer self-update` and see if the problem persists afterwards.

**Comment by dbierer** [comment]
Matthew -- still testing.  Will do as you suggested and report back.  If all works OK will close the issue.  Thx for the quick response!

**Comment by dbierer** [comment]
Updated to Composer 1.10.x.  Working perfectly now.  Thanks!
