### ISSUE TITLE
Adds support for composer/semver 3.0 (and maybe 1.0?)

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-migration#43]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

[composer/semver 3.0](https://github.com/composer/semver/releases/tag/3.0.0) has been just released. We need add support for it.

Not sure also why we are using just v2.0, and not supporting v1.0? As we suggest installing migration tool globally, we should support the widest dependency range, imo.

**Comment by weierophinney** [comment]
Honestly, I hadn't considered that the previous major version was viable. If the interface we consume is the same, I see no reason not to use it.
