### ISSUE TITLE
Migration does not rename composer.json `extra.zf` to `extra.laminas`

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-migration#56]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.2.2

#### Summary

When migrating packages which provide informations for the `laminas-component-installer`, the `extra.zf` entry is not being renamed to `extra.laminas`.

#### Current behavior

`extra.zf` is still present in `composer.json`

#### How to reproduce

```json
{
    "extra": { 
        "zf": {}
    }
}
```

Try to migrate this `composer.json`.

#### Expected behavior

`extra.zf` is being renamed to `extra.laminas`.

**Comment by weierophinney** [comment]
Fixed with #58.
