### ISSUE TITLE
Support for PHP 8.1

### ISSUE THREAD

**Issue by pixeldev** [laminas/laminas-migration#65]
I was wondering if this package will be available for PHP 8.1 soon, since I need it to update a Magento project which was upgraded from 2.3.2 to 2.4.4.

**Comment by weierophinney** [comment]
Do you see any errors currently when running it under PHP 8.1? If so, can you provide error messages, please?

**Comment by Ocramius** [comment]
AFAIK, composer.json doesn't allow for PHP 8.1 here yet: send a patch, ans CI will verify compatibility

**Comment by Ocramius** [comment]
Ref https://github.com/laminas/laminas-migration/blob/d7f569db79fdfbb56191528229b1a89cab9f02e0/composer.json#L15

**Comment by boesing** [comment]
I guess one of the main reasons for this is that we do rely on `PHPCompatibility` codechecker here which does not really support PHP 8.0+

It seems that when we migrated to the GHA, we dropped the `check-compat` composer script call anyways and thus we can also just remove it. Psalm should already ensure that we do not use functions which are only available in more recent PHP versions.

**Comment by Ocramius** [comment]
We can probably drop it from CI overall
